name: IPTV All

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *"  # 每天晚上4:00执行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Download ChromeDriver
        uses: s1monov/setup-chromedriver@v1
        with:
          version: '120.0.6099.109'

      - name: Set chromedriver path
        run: |
          sudo ln -sf ${{ runner.temp }}/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run script
        run: python ${{ github.workspace }}/IPTV.py

      - name: 提交更改
        run: |
          git config --global user.email "365862988@qq.com"
          git config --global user.name "cmzliu3658"
          git add .
          git commit -m "Add generated file"
          git push -f
