name: IPTV All

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests eventlet

      - name: Install Chrome WebDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=133.0.6943.98
          curl -sS -o chromedriver-linux64.zip "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip -d /usr/local/bin
          rm chromedriver-linux64.zip

      - name: Set chromedriver path
        run: |
          sudo ln -sf /usr/local/bin/chromedriver-linux64 /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run script
        run: python ${{ github.workspace }}/IPTV.py

      - name: Commit changes
        run: |
          git config --global user.email "365862988@qq.com"
          git config --global user.name "cmzliu3658"
          git add .
          git commit -m "Add generated file"
          git push -f
